name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php: [8.2, 8.3, 8.4]
        packages:
          - { laravel: ^11.0,  testbench: ^9.0, phpunit: 10.5.* }
          - { laravel: ^12.0,  testbench: ^10.0, phpunit: 11.5.* }

    name: phpunit (PHP:${{ matrix.php }}, Laravel:${{ matrix.packages.laravel }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install dependencies
        run: |
          composer require \
            "illuminate/support:${{ matrix.packages.laravel }}" \
            "phpunit/phpunit:${{ matrix.packages.phpunit }}" \
            "orchestra/testbench:${{ matrix.packages.testbench }}" \
            --no-interaction --no-update

          composer install --no-interaction --prefer-dist --no-progress

      - name: Tests
        run: ./vendor/bin/phpunit
